### ISSUE TITLE
Testing coverage for basic application

### ISSUE THREAD

**Issue by aterrel** [memex-explorer/memex-explorer#292]
- [x] add coveralls to Django model apps (thanks @brittainhard!)
- [ ] Set up web service to use local crawlers for functional testing
- [x] Test functional interactions with application (Selenium)

**Comment by brittainhard** [comment]
Done.
