### ISSUE TITLE
Image Space -- similarity measures

### ISSUE THREAD

**Issue by aterrel** [memex-explorer/memex-explorer#293]
- [ ] Add alternative similarity measures to Image Space
  - [ ] Histogram image similarity
  - [ ] Jaccard similarity from @chrismattmann 
  - [ ] Kitware face detection
  - [ ] CMU similarity measure (see MEMEX WIKI)
- [ ] Convert Django application

**Comment by brittainhard** [comment]
The current image space app will not be written in Django.
