### ISSUE TITLE
Topic Space - microservice

### ISSUE THREAD

**Issue by aterrel** [memex-explorer/memex-explorer#294]
- [ ] Release microservice style code
- [ ] Interactive visuals including termite, wordcloud, and histograms of topics
- [ ] Easy update domain dictionaries

**Comment by aterrel** [comment]
Separated topik and topic_space.

**Comment by brittainhard** [comment]
This is now in a separate repository.
